<?php

namespace Database\Seeders;

use App\Models\Kecamatan;
use App\Models\ObjekWisata;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ObjekWisataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $komodo = Kecamatan::where('nama_kecamatan', 'Komodo')->first();
        $sano = Kecamatan::where('nama_kecamatan', 'Sano Nggoang')->first();
        $boleng = Kecamatan::where('nama_kecamatan', 'Boleng')->first();

        $wisatas = [
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Gua Rangko',
                'alamat' => 'Desa Rangko, Kec. Komodo',
                'no_telepon' => '081234567890',
                'keterangan' => 'Gua dengan kolam air asin berwarna biru jernih yang sangat indah.',
                'daya_tarik_utama' => 'Kolam air asin alami yang jernih di dalam gua yang bisa digunakan untuk berenang.',
                'jam_operasional' => '08:00 - 17:00 WITA',
                'harga_tiket' => '20000',
                'harga_tiket_lokal' => 20000,
                'harga_tiket_domestik' => 15000,
                'harga_tiket_asing' => 30000,
                'harga_parkir_motor' => 2000,
                'harga_parkir_mobil' => 5000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)', 'Kendaraan Pribadi (Mobil)'],
                'latitude' => -8.4526,
                'longitude' => 119.923889,
            ],
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Gua Batu Cermin',
                'alamat' => 'Batu Cermin, Labuan Bajo, Kec. Komodo',
                'no_telepon' => '081234567891',
                'keterangan' => 'Gua yang memiliki dinding yang memantulkan cahaya seperti cermin.',
                'daya_tarik_utama' => 'Dinding gua purba yang bersinar saat terkena cahaya matahari, mirip dengan cermin.',
                'jam_operasional' => '09:00 - 18:00 WITA',
                'harga_tiket' => '50000',
                'harga_tiket_lokal' => 50000,
                'harga_tiket_domestik' => 40000,
                'harga_tiket_asing' => 75000,
                'harga_parkir_motor' => 3000,
                'harga_parkir_mobil' => 10000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)', 'Kendaraan Pribadi (Mobil)', 'Kendaraan Umum / Angkot'],
                'latitude' => -8.484444,
                'longitude' => 119.896111,
            ],
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Bukit Raja',
                'alamat' => 'Labuan Bajo, Kec. Komodo',
                'no_telepon' => '081234567892',
                'keterangan' => 'Bukit dengan pemandangan sunset yang spektakuler di Labuan Bajo.',
                'daya_tarik_utama' => 'Titik pandang terbaik untuk menyaksikan matahari terbenam dengan latar belakang pelabuhan Labuan Bajo.',
                'jam_operasional' => '05:00 - 19:00 WITA',
                'harga_tiket' => '0',
                'harga_tiket_lokal' => 0,
                'harga_tiket_domestik' => 0,
                'harga_tiket_asing' => 0,
                'harga_parkir_motor' => 2000,
                'harga_parkir_mobil' => 5000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)'],
                'latitude' => -8.491667,
                'longitude' => 119.883333,
            ],
            [
                'id_kecamatan' => $sano->id ?? 2,
                'nama_objek' => 'Cunca Pilas',
                'alamat' => 'Desa Wae Lolos, Kec. Sano Nggoang',
                'no_telepon' => '081234567893',
                'keterangan' => 'Air terjun yang dikelilingi oleh hutan hijau yang asri.',
                'daya_tarik_utama' => 'Kesejukan air terjun alami di tengah hutan tropis yang sangat tenang dan damai.',
                'jam_operasional' => '08:00 - 16:00 WITA',
                'harga_tiket' => '10000',
                'harga_tiket_lokal' => 10000,
                'harga_tiket_domestik' => 10000,
                'harga_tiket_asing' => 15000,
                'harga_parkir_motor' => 2000,
                'harga_parkir_mobil' => 5000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)'],
                'latitude' => -8.621111,
                'longitude' => 120.012500,
            ],
            [
                'id_kecamatan' => $sano->id ?? 2,
                'nama_objek' => 'Cunca Rami',
                'alamat' => 'Desa Golo Loni, Kec. Sano Nggoang',
                'no_telepon' => '081234567894',
                'keterangan' => 'Air terjun tertinggi di Manggarai Barat dengan debit air yang besar.',
                'daya_tarik_utama' => 'Air terjun setinggi 30 meter dengan kolam renang alami yang luas di bawahnya.',
                'jam_operasional' => '08:00 - 17:00 WITA',
                'harga_tiket' => '20000',
                'harga_tiket_lokal' => 20000,
                'harga_tiket_domestik' => 20000,
                'harga_tiket_asing' => 30000,
                'harga_parkir_motor' => 2000,
                'harga_parkir_mobil' => 5000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)', 'Bisa Dijangkau Jalan Kaki'],
                'latitude' => -8.654722,
                'longitude' => 120.086111,
            ],
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Pantai Pede',
                'alamat' => 'Jl. Pantai Pede, Labuan Bajo, Kec. Komodo',
                'no_telepon' => '081234567895',
                'keterangan' => 'Pantai publik di Labuan Bajo yang sering digunakan untuk bersantai.',
                'daya_tarik_utama' => 'Pantai pasir putih yang mudah diakses dari pusat kota untuk menikmati suasana pantai saat sore hari.',
                'jam_operasional' => '05:00 - 20:00 WITA',
                'harga_tiket' => '0',
                'harga_tiket_lokal' => 0,
                'harga_tiket_domestik' => 0,
                'harga_tiket_asing' => 0,
                'harga_parkir_motor' => 2000,
                'harga_parkir_mobil' => 5000,
                'akses_transportasi' => ['Kendaraan Pribadi (Motor)', 'Kendaraan Pribadi (Mobil)', 'Kendaraan Umum / Angkot'],
                'latitude' => -8.508333,
                'longitude' => 119.875000,
            ],
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Pulau Komodo',
                'alamat' => 'Taman Nasional Komodo, Kec. Komodo',
                'no_telepon' => '081234567896',
                'keterangan' => 'Habitat asli hewan purba Komodo yang dilindungi dunia.',
                'daya_tarik_utama' => 'Pengalaman melihat langsung hewan purba Komodo (Varanus komodoensis) di habitat aslinya.',
                'jam_operasional' => '07:00 - 16:00 WITA',
                'harga_tiket' => '250000',
                'harga_tiket_lokal' => 150000,
                'harga_tiket_domestik' => 250000,
                'harga_tiket_asing' => 500000,
                'harga_parkir_motor' => 0,
                'harga_parkir_mobil' => 0,
                'akses_transportasi' => ['Bus Pariwisata', 'Lainnya (Speedboat)'],
                'latitude' => -8.583333,
                'longitude' => 119.500000,
            ],
            [
                'id_kecamatan' => $boleng->id ?? 6,
                'nama_objek' => 'Pulau Gili Laba',
                'alamat' => 'Kec. Boleng, Manggarai Barat',
                'no_telepon' => '081234567897',
                'keterangan' => 'Pulau cantik dengan bukit savana yang menawarkan pemandangan laut 360 derajat.',
                'daya_tarik_utama' => 'Hiking ke puncak bukit untuk melihat panorama teluk yang sangat ikonik dan gradasi air laut.',
                'jam_operasional' => '05:00 - 18:00 WITA',
                'harga_tiket' => '50000',
                'harga_tiket_lokal' => 50000,
                'harga_tiket_domestik' => 50000,
                'harga_tiket_asing' => 100000,
                'harga_parkir_motor' => 0,
                'harga_parkir_mobil' => 0,
                'akses_transportasi' => ['Lainnya (Kapal Phinisi)'],
                'latitude' => -8.383333,
                'longitude' => 119.633333,
            ],
            [
                'id_kecamatan' => $komodo->id ?? 1,
                'nama_objek' => 'Pulau Padar',
                'alamat' => 'Taman Nasional Komodo, Kec. Komodo',
                'no_telepon' => '081234567898',
                'keterangan' => 'Pulau ikonik dengan tiga teluk dengan warna pasir yang berbeda.',
                'daya_tarik_utama' => 'Pemandangan spektakuler dari puncak bukit yang memperlihatkan tiga pantai (pasir putih, pink, dan hitam).',
                'jam_operasional' => '05:00 - 17:00 WITA',
                'harga_tiket' => '150000',
                'harga_tiket_lokal' => 100000,
                'harga_tiket_domestik' => 150000,
                'harga_tiket_asing' => 250000,
                'harga_parkir_motor' => 0,
                'harga_parkir_mobil' => 0,
                'akses_transportasi' => ['Lainnya (Speedboat)'],
                'latitude' => -8.650000,
                'longitude' => 119.566667,
            ],
            [
                'id_kecamatan' => $boleng->id ?? 6,
                'nama_objek' => 'Pulau Kanawa',
                'alamat' => 'Kec. Boleng, Manggarai Barat',
                'no_telepon' => '081234567899',
                'keterangan' => 'Pulau dengan taman bawah laut yang sangat indah untuk snorkeling.',
                'daya_tarik_utama' => 'Pasir putih yang lembut dan kejernihan air yang memungkinkan snorkeling langsung dari pinggir pantai.',
                'jam_operasional' => '08:00 - 17:00 WITA',
                'harga_tiket' => '50000',
                'harga_tiket_lokal' => 50000,
                'harga_tiket_domestik' => 50000,
                'harga_tiket_asing' => 100000,
                'harga_parkir_motor' => 0,
                'harga_parkir_mobil' => 0,
                'akses_transportasi' => ['Lainnya (Speedboat)'],
                'latitude' => -8.497222,
                'longitude' => 119.758333,
            ],
        ];

        foreach ($wisatas as $wisata) {
            ObjekWisata::updateOrCreate(
                ['nama_objek' => $wisata['nama_objek']],
                $wisata
            );
        }
    }
}
